/// FFI-backed repository — drop-in replacement for the HTTP LedgerRepository.
///
/// Instead of making HTTP requests, every method calls the generated Dart
/// bindings that talk directly to the compiled Rust library.
///
/// The generated functions live in lib/src/rust/frb_generated.dart and are
/// produced by running:
///
///   dart run flutter_rust_bridge_codegen generate
///
/// Naming convention (flutter_rust_bridge v2):
///   Rust  fn list_accounts()  →  Dart  listAccounts()
///   Rust  fn open_cash_account(name, ..)  →  Dart  openCashAccount(name: ..)
///
/// All generated functions are top-level async Dart functions that return
/// the same primitive-struct DTOs defined in ledger::interface::ffi.
/// We map those onto the existing Dart model classes so nothing else in the
/// app needs to change.

import '../../models/account_summary.dart';
import '../../models/net_worth_result.dart';
import '../../models/ledger_entry.dart';
import '../../models/credit_card_info.dart';
import '../../models/account_detail.dart';
import '../../models/statement.dart';

// Generated by flutter_rust_bridge_codegen — will exist after you run codegen.
import '../../../src/rust/frb_generated.dart';

// ── Error handling ────────────────────────────────────────────────────────────

/// Matches ApiException so the rest of the app doesn't need to change.
class ApiException implements Exception {
  final int statusCode;
  final String message;
  const ApiException(this.statusCode, this.message);

  bool get isNotFound => message.contains('not found') || message.contains('NotFound');

  @override
  String toString() => 'FfiException: $message';
}

/// Wraps a Rust Result<T, String> — the FFI functions return either a value
/// or throw a String error. We convert that into ApiException.
T _unwrap<T>(T value) => value; // generated fns throw on Err automatically

/// Rust errors come back as thrown Strings from the generated bindings.
/// We catch them and wrap in ApiException so existing error-handling works.
Never _throw(Object err) =>
    throw ApiException(500, err.toString());

// ── Repository ────────────────────────────────────────────────────────────────

class FfiRepository {
  const FfiRepository();

  // ── Lifecycle ──────────────────────────────────────────────────────────────

  /// Called once at startup to create the user finances record if absent.
  /// The db is already open at this point (done in main.dart via initDb).
  Future<void> init() async {
    try {
      await initFinances();
    } catch (e) {
      // FinancesNotFound means it was already initialised — ignore.
      if (!e.toString().contains('already')) _throw(e);
    }
  }

  // ── Queries ────────────────────────────────────────────────────────────────

  Future<List<AccountSummary>> listAccounts() async {
    try {
      final results = await listAccounts();
      return results.map((r) => AccountSummary(
        accountId:   r.accountId,
        accountName: r.accountName,
        accountType: r.accountType,
        currency:    r.currency,
        balance:     r.balance,
        isDebt:      r.isDebt,
        isOverdue:   r.isOverdue,
      )).toList();
    } catch (e) { _throw(e); }
  }

  Future<List<NetWorthResult>> getNetWorth({String? currency}) async {
    try {
      final results = await netWorth(currency: currency);
      return results.map((r) => NetWorthResult(
        currency:     r.currency,
        totalAssets:  r.totalAssets,
        totalDebts:   r.totalDebts,
        netWorth:     r.netWorth,
        isDeficit:    r.isDeficit,
      )).toList();
    } catch (e) { _throw(e); }
  }

  // ── Account detail ─────────────────────────────────────────────────────────

  Future<CashAccountDetail> getCashDetail(String id) async {
    try {
      final r = await cashDetail(accountId: id);
      return CashAccountDetail(
        accountId: r.accountId, accountName: r.accountName,
        currency: r.currency,  balance: r.balance,
        bank: r.bank,          accountNumber: r.accountNumber,
      );
    } catch (e) { _throw(e); }
  }

  Future<PhysicalWalletDetail> getWalletDetail(String id) async {
    try {
      final r = await walletDetail(accountId: id);
      return PhysicalWalletDetail(
        accountId: r.accountId, accountName: r.accountName,
        currency: r.currency,  balance: r.balance,
      );
    } catch (e) { _throw(e); }
  }

  Future<DigitalWalletDetail> getDigitalWalletDetail(String id) async {
    try {
      final r = await digitalWalletDetail(accountId: id);
      return DigitalWalletDetail(
        accountId: r.accountId,    accountName: r.accountName,
        currency: r.currency,      balance: r.balance,
        provider: r.provider,      providerAccountId: r.providerAccountId,
      );
    } catch (e) { _throw(e); }
  }

  Future<InvestmentAccountDetail> getInvestmentDetail(String id) async {
    try {
      final r = await investmentDetail(accountId: id);
      return InvestmentAccountDetail(
        accountId:     r.accountId,     accountName:   r.accountName,
        currency:      r.currency,      cashBalance:   r.cashBalance,
        holdingsValue: r.holdingsValue, totalValue:    r.totalValue,
        bank:          r.bank,          accountNumber: r.accountNumber,
        holdings: r.holdings.map((h) => HoldingDetail(
          ticker:         h.ticker,         investmentType: h.investmentType,
          quantity:       h.quantity,       unitPrice:      h.unitPrice,
          marketValue:    h.marketValue,    currency:       h.currency,
        )).toList(),
      );
    } catch (e) { _throw(e); }
  }

  Future<LoanAccountDetail> getLoanDetail(String id) async {
    try {
      final r = await loanDetail(accountId: id);
      return LoanAccountDetail(
        accountId:      r.accountId,     accountName:    r.accountName,
        currency:       r.currency,      bank:           r.bank,
        accountNumber:  r.accountNumber, creditor:       r.creditor,
        principal:      r.principal,     outstanding:    r.outstanding,
        amountPaid:     r.amountPaid,    percentPaid:    r.percentPaid,
        interestRate:   r.interestRate != null
                          ? double.tryParse(r.interestRate!) : null,
        dueDay:         r.dueDay,        maturityDate:   r.maturityDate,
        minimumPayment: r.minimumPayment,
        isOverdue:      r.isOverdue,     isSettled:      r.isSettled,
      );
    } catch (e) { _throw(e); }
  }

  Future<CreditCardInfo> getCreditCardInfo(String id) async {
    try {
      // Credit card detail comes from the same card_info handler.
      // The FFI exposes it via the investment_detail path for the card type.
      // The generated binding will be getCreditCardInfo(accountId: id).
      final r = await getCreditCardInfo(accountId: id);
      return CreditCardInfo.fromFfi(r);
    } catch (e) { _throw(e); }
  }

  // ── Account management ─────────────────────────────────────────────────────

  Future<void> openCashAccount({
    required String name, required String accountNumber,
    required String bank, required String currency,
    required String initialBalance,
  }) async {
    try {
      await openCashAccount(
        name: name, accountNumber: accountNumber, bank: bank,
        currency: currency, initialBalance: initialBalance,
      );
    } catch (e) { _throw(e); }
  }

  Future<void> addPhysicalWallet({
    required String name, required String currency,
    required String initialBalance,
  }) async {
    try {
      await addPhysicalWallet(name: name, currency: currency, initialBalance: initialBalance);
    } catch (e) { _throw(e); }
  }

  Future<void> addDigitalWallet({
    required String name, required String provider,
    required String providerAccountId, required String currency,
    required String initialBalance,
  }) async {
    try {
      await addDigitalWallet(
        name: name, provider: provider, providerAccountId: providerAccountId,
        currency: currency, initialBalance: initialBalance,
      );
    } catch (e) { _throw(e); }
  }

  Future<void> openInvestmentAccount({
    required String name, required String accountNumber,
    required String bank, required String currency,
    required String cashBalance,
  }) async {
    try {
      await openInvestmentAccount(
        name: name, accountNumber: accountNumber, bank: bank,
        currency: currency, cashBalance: cashBalance,
      );
    } catch (e) { _throw(e); }
  }

  Future<void> addCreditCard({
    required String name, required String lastFour, required String network,
    required int expiryMonth, required int expiryYear,
    required String creditLimit, required String currency,
    required String outstanding, required int statementDay, required int dueDay,
    String? interestRate,
  }) async {
    try {
      await addCreditCard(
        name: name, lastFour: lastFour, network: network,
        expiryMonth: expiryMonth, expiryYear: expiryYear,
        creditLimit: creditLimit, currency: currency,
        outstanding: outstanding, statementDay: statementDay, dueDay: dueDay,
        interestRate: interestRate,
      );
    } catch (e) { _throw(e); }
  }

  Future<void> openLoan({
    required String name, required String bank, required String creditor,
    required String currency, required String principal,
    String? accountNumber, String? interestRate,
    int? dueDay, String? maturityDate, String? minimumPayment,
  }) async {
    try {
      await openLoanAccount(
        name: name, bank: bank, creditor: creditor,
        currency: currency, principal: principal,
        accountNumber: accountNumber, interestRate: interestRate,
        dueDay: dueDay, maturityDate: maturityDate,
        minimumPayment: minimumPayment,
      );
    } catch (e) { _throw(e); }
  }

  Future<void> removeAccount(String accountId) async {
    try { await removeAccount(accountId: accountId); }
    catch (e) { _throw(e); }
  }

  Future<void> updateAccountInfo(String accountId, {
    String? name, String? bank, String? accountNumber,
  }) async {
    try {
      await updateAccountInfo(
        accountId: accountId, name: name, bank: bank, accountNumber: accountNumber,
      );
    } catch (e) { _throw(e); }
  }

  // ── Transactions ───────────────────────────────────────────────────────────

  Future<void> deposit(String accountId, String amount, String currency,
      {String? label, String? description}) async {
    try {
      await deposit(
        accountId: accountId, amount: amount, currency: currency,
        label: label, description: description,
      );
    } catch (e) { _throw(e); }
  }

  Future<void> withdraw(String accountId, String amount, String currency,
      {String? label, String? description}) async {
    try {
      await withdraw(
        accountId: accountId, amount: amount, currency: currency,
        label: label, description: description,
      );
    } catch (e) { _throw(e); }
  }

  Future<void> charge(String accountId, String amount, String currency,
      {String? label, String? description}) async {
    try {
      await charge(
        accountId: accountId, amount: amount, currency: currency,
        label: label, description: description,
      );
    } catch (e) { _throw(e); }
  }

  Future<void> pay({
    required String debtAccountId, required String fromAccountId,
    required String amount, required String currency,
    String? label, String? description,
  }) async {
    try {
      await pay(
        accountId: debtAccountId, fromAccountId: fromAccountId,
        amount: amount, currency: currency,
        label: label, description: description,
      );
    } catch (e) { _throw(e); }
  }

  Future<void> transferFunds({
    required String fromAccountId, required String toAccountId,
    required String amount, required String currency,
    String? label, String? description,
  }) async {
    try {
      await transfer(
        from: fromAccountId, to: toAccountId,
        amount: amount, currency: currency,
        label: label, description: description,
      );
    } catch (e) { _throw(e); }
  }

  Future<void> accrueInterest(String accountId) async {
    try { await accrueInterest(accountId: accountId); }
    catch (e) { _throw(e); }
  }

  Future<void> grantTemporaryLimit({
    required String accountId, required String newLimit,
    required String currency, required String expiresOn,
  }) async {
    try {
      await grantLimit(
        accountId: accountId, newLimit: newLimit,
        currency: currency, expiresOn: expiresOn,
      );
    } catch (e) { _throw(e); }
  }

  Future<void> revokeTemporaryLimit(String accountId) async {
    try { await revokeLimit(accountId: accountId); }
    catch (e) { _throw(e); }
  }

  Future<void> closeStatement({
    required String accountId, String? minimumPayment,
    required String currency,
  }) async {
    try {
      await closeStatement(
        accountId: accountId, minimumPayment: minimumPayment,
        currency: currency,
      );
    } catch (e) { _throw(e); }
  }

  // ── Holdings ───────────────────────────────────────────────────────────────

  Future<void> addHolding({
    required String accountId, required String ticker,
    required String investmentType, required String quantity,
    required String unitPrice, required String currency,
  }) async {
    try {
      await addHolding(
        accountId: accountId, ticker: ticker,
        quantity: quantity, unitPrice: unitPrice,
        currency: currency, investmentType: investmentType,
      );
    } catch (e) { _throw(e); }
  }

  Future<void> removeHolding(String accountId, String ticker) async {
    try { await removeHolding(accountId: accountId, ticker: ticker); }
    catch (e) { _throw(e); }
  }

  Future<void> updateHoldingPrice({
    required String accountId, required String ticker,
    required String newPrice, required String currency,
  }) async {
    try {
      await updateHoldingPrice(
        accountId: accountId, ticker: ticker,
        newPrice: newPrice, currency: currency,
      );
    } catch (e) { _throw(e); }
  }

  // ── Ledger entries ─────────────────────────────────────────────────────────

  Future<List<LedgerEntry>> listEntries(String accountId) async {
    try {
      final results = await listEntries(accountId: accountId);
      return results.map((e) => LedgerEntry(
        id:          e.id,
        accountId:   e.accountId,
        entryType:   e.entryType,
        amount:      e.amount,
        currency:    e.currency,
        occurredAt:  e.occurredAt,
        label:       e.label,
        description: e.description,
      )).toList();
    } catch (e) { _throw(e); }
  }

  Future<void> updateAnnotation(String entryId, {
    String? label, String? description,
  }) async {
    try {
      await updateEntryAnnotation(
        entryId: entryId, label: label, description: description,
      );
    } catch (e) { _throw(e); }
  }

  // ── Statements ─────────────────────────────────────────────────────────────

  Future<List<Statement>> listStatements(String accountId) async {
    try {
      final results = await listStatements(accountId: accountId);
      return results.map((s) => Statement(
        id:               s.id,
        accountId:        s.accountId,
        cycleStart:       s.cycleStart,
        cycleEnd:         s.cycleEnd,
        statementBalance: s.statementBalance,
        minimumPayment:   s.minimumPayment,
        totalCharged:     s.totalCharged,
        totalPaid:        s.totalPaid,
        isSettled:        s.isSettled,
      )).toList();
    } catch (e) { _throw(e); }
  }

  Future<List<LedgerEntry>> statementEntries(
      String accountId, String statementId) async {
    // The FFI layer doesn't have a dedicated statement-entries function —
    // it returns all entries and the caller filters by date range, exactly
    // as the HTTP statement_entries handler does internally.
    // We fetch all entries and filter client-side using the statement dates.
    try {
      final stmts = await listStatements(accountId: accountId);
      final stmt  = stmts.firstWhere(
        (s) => s.id == statementId,
        orElse: () => throw 'Statement $statementId not found',
      );
      final all = await listEntries(accountId: accountId);
      final start = DateTime.parse(stmt.cycleStart);
      final end   = DateTime.parse(stmt.cycleEnd)
                        .add(const Duration(hours: 23, minutes: 59, seconds: 59));
      return all.where((e) {
        final t = DateTime.parse(e.occurredAt);
        return t.isAfter(start.subtract(const Duration(seconds: 1))) &&
               t.isBefore(end.add(const Duration(seconds: 1)));
      }).toList();
    } catch (e) { _throw(e); }
  }

  // Alias methods used by the existing screens (same signatures as HTTP repo)
  Future<void> depositWithAnnotation(
    String accountId, String amount, String currency, {
    String? label, String? description,
  }) => deposit(accountId, amount, currency, label: label, description: description);

  Future<void> withdrawWithAnnotation(
    String accountId, String amount, String currency, {
    String? label, String? description,
  }) => withdraw(accountId, amount, currency, label: label, description: description);

  Future<void> chargeWithAnnotation(
    String accountId, String amount, String currency, {
    String? label, String? description,
  }) => charge(accountId, amount, currency, label: label, description: description);

  Future<void> payWithAnnotation({
    required String debtAccountId, required String fromAccountId,
    required String amount, required String currency,
    String? label, String? description,
  }) => pay(
    debtAccountId: debtAccountId, fromAccountId: fromAccountId,
    amount: amount, currency: currency,
    label: label, description: description,
  );
}
