[package]
name = "iam"
version = "0.1.0"
edition = "2024"

[dependencies]
shared= { path = "../shared" }
async-trait = "0.1.89"
chrono = { version = "0.4.43", features = ["serde"] }
rust_decimal = "1.40.0"
thiserror = "2.0.18"
uuid = { version = "1.20.0", features = ["serde", "v4"] }
enum_dispatch = "0.3"
phonenumber = { version = "0.3.9" }
serde = { version = "1.0.228", features = ["derive"] }
