import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:path_provider/path_provider.dart';
import 'core/providers.dart';
import 'screens/shell/app_shell.dart';
import 'screens/onboarding/onboarding_screen.dart';
import 'theme/app_theme.dart';

// Generated by flutter_rust_bridge_codegen
import '../src/rust/frb_generated.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ── 1. Initialise the flutter_rust_bridge runtime ─────────────────────────
  await RustLib.init();

  // ── 2. Resolve the database path ──────────────────────────────────────────
  //
  // On mobile, app documents directory is the right place — it is private
  // to the app, persists across updates, and is backed up on iOS.
  //
  // On desktop (if you ever run it there too), the same call works.
  final dbPath = await _resolveDbPath();

  // ── 3. Open the SQLite database inside Rust ───────────────────────────────
  //
  // initDb() is generated from ledger::interface::ffi::init().
  // It creates the db file and runs migrations if needed.
  // Subsequent calls with the same path are silently ignored.
  await initDb(dbPath: dbPath, userId: null);

  runApp(const ProviderScope(child: NetflowApp()));
}

Future<String> _resolveDbPath() async {
  final dir = await getApplicationDocumentsDirectory();
  final dataDir = Directory('${dir.path}/netflow');
  if (!await dataDir.exists()) await dataDir.create(recursive: true);
  return '${dataDir.path}/netflow.db';
}

class NetflowApp extends StatelessWidget {
  const NetflowApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'netflow',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.dark,
      darkTheme: AppTheme.dark,
      themeMode: ThemeMode.dark,
      home: const _AppRouter(),
    );
  }
}

class _AppRouter extends ConsumerWidget {
  const _AppRouter();

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final bootstrap = ref.watch(bootstrapProvider);

    return bootstrap.when(
      loading: () => const Scaffold(
        body: Center(child: CircularProgressIndicator()),
      ),

      // FFI errors are plain strings, not network errors —
      // show the message directly rather than "Cannot reach server".
      error: (e, _) => Scaffold(
        body: SafeArea(
          child: Padding(
            padding: const EdgeInsets.all(32),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                const Icon(Icons.error_outline_rounded,
                    size: 56, color: AppTheme.red),
                const SizedBox(height: 20),
                Text('Something went wrong',
                    style: Theme.of(context).textTheme.titleLarge,
                    textAlign: TextAlign.center),
                const SizedBox(height: 8),
                Text(e.toString(),
                    style: Theme.of(context).textTheme.bodySmall,
                    textAlign: TextAlign.center),
                const SizedBox(height: 32),
                FilledButton.icon(
                  onPressed: () => ref.invalidate(bootstrapProvider),
                  icon: const Icon(Icons.refresh_rounded),
                  label: const Text('Retry'),
                ),
              ],
            ),
          ),
        ),
      ),

      data: (isInitialised) =>
          isInitialised ? const AppShell() : const OnboardingScreen(),
    );
  }
}
